services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:2.8.3@sha256:f9b43b696fcbf52f3b20a0121efd3e895543dd085ed13edb54593d614e65eb7a
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /opt/stacks/heimdall:/config
    ports:
      - "${HEIMDALL_BIND_IP:-127.0.0.1}:80:80"
    restart: unless-stopped
