services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:2.8.3@sha256:3c9e97c416c7f6d72a3fc12af01a37bd0e71d9e6588d25c40b47e391f39ff7fd
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /opt/stacks/heimdall:/config
    ports:
      - "${HEIMDALL_BIND_IP:-127.0.0.1}:80:80"
    restart: unless-stopped
