services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:2.7.6@sha256:8a2f8cd61546454e4bcbfcda9a88f4cb190a69e6f7ad7596b5db8bda18ea5818
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /opt/stacks/heimdall:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
